### ISSUE TITLE
KeyError: 'definitions'

### ISSUE THREAD

**Issue by francisra75** [akamai-contrib/cli-jsonnet#6] opened 2022-06-03 11:46 UTC
Is jsonnet-cli still compatible with the current akamai API?

My akamai jsonnet cli stopped working. I always get this KeyError.

akamai jsonnet papi ruleformat  --productId Fresca
Traceback (most recent call last):
  File "/Users/rastrfra/.akamai-cli/venv/cli-jsonnet/lib/python3.9/site-packages/jsonpointer.py", line 288, in walk
    return doc[part]
KeyError: 'definitions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/bin/akamai-jsonnet", line 9, in <module>
    main()
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/main.py", line 12, in main
    args.func(args)
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/main.py", line 60, in <lambda>
    parser.set_defaults(func=lambda args: ruleformat(**vars(args)))
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/commands/papi.py", line 22, in ruleformat
    converter.convert(writer)
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/jsonnet/papi/converter/ruleformat.py", line 16, in convert
    self.convert_behaviors(writer)
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/jsonnet/papi/converter/ruleformat.py", line 72, in convert_behaviors
    behaviors = self.ruleFormat.resolve_pointer("/definitions/catalog/behaviors")
  File "/Users/rastrfra/.akamai-cli/src/cli-jsonnet/src/jsonnet/papi/ruleformat.py", line 25, in resolve_pointer
    return resolve_pointer(self.schema, ptr.lstrip("#"))
  File "/Users/rastrfra/.akamai-cli/venv/cli-jsonnet/lib/python3.9/site-packages/jsonpointer.py", line 128, in resolve_pointer
    return pointer.resolve(doc, default)
  File "/Users/rastrfra/.akamai-cli/venv/cli-jsonnet/lib/python3.9/site-packages/jsonpointer.py", line 206, in resolve
    doc = self.walk(doc, part)
  File "/Users/rastrfra/.akamai-cli/venv/cli-jsonnet/lib/python3.9/site-packages/jsonpointer.py", line 291, in walk
    raise JsonPointerException("member '%s' not found in %s" % (part, doc))

**Comment by ynohat** [comment] 2023-06-20 17:20
Hi @francisra75 apologies for the very long delay; I am unable to reproduce the issue unfortunately so will close this for now.
This is still in use with more recent rule formats and is working fine.

**Closed as completed by ynohat** 2023-06-20 17:20 UTC
